spring.application.name=ems-backend

# Local MySQL database
spring.datasource.url=jdbc:mysql://localhost:3306/ems
spring.datasource.username=root
spring.datasource.password=

#hibernate uses this dialect to create the SQL statement based in the database that we are using
#hibernate will create the SQL statements that are compatible with MySQL database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Use 'update' for local development only. Do not use in production.
spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true